name: Mobile App Test
on: [push]

jobs:
  test:
    name: Unit Test Test Mobile App
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v2

    - name: Angular Github Actions
      uses: mayur-rawte/github-angular-actions@latest
      
    - name: install dependencies, test
      working-directory: ./apps/VZ200-App
      run: |
        pwd
        ls
        npm ci
        npm test
